### ISSUE TITLE
移动端无法移动选择框

### ISSUE THREAD

**Issue by 52manhua** [zimv/zmCanvasCrop#2]
电脑端调试没大问题，不过移动端 android 的 firefox 不能移动图片选框，有没有什么解决办法？

应该是需要添加 移动端的 touch 事件，或者简单一点增加移动 选择框的按钮
后者比较简单，不过看事件的导出有点困难，
有什么提示吗？

**Comment by zimv** [comment]
这个当时只做了鼠标点击，按理来说目前有很多三方的插件写的比我这个好多了，我这个当时就是个demo，也并没有再去完善了。你去找找其他的库来用吧，我这个太垃圾了

**Comment by 52manhua** [comment]
刚好有个简单的项目挺好用，

想引出 canvas.overlay 选择框 的 top 和 left 属性，有没有什么提示？

先谢谢

我也找了一下其他插件，完全基于 base64 的挺少见，
有的插件只实现了前端功能，后端要 php-gd 插件，有的又是  blob 格式，嵌入很困难

**Comment by zimv** [comment]
我有点没懂你说的提示的意思，我那个代码也不多，你把原理搞清楚了 改造一下把
